const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGOUT = "LOGOUT";

const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILURE = "REGISTER_FAILURE";

const COULD_NOT_CONNECT_TO_SERVER = "COULD_NOT_CONNECT_TO_SERVER";

const COULD_NOT_DECODE_TOKEN = "COULD_NOT_DECODE_TOKEN";

const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

const USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS";
const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";

const USER_FOUND = "USER_FOUND";
const USER_NOT_FOUND = "USER_NOT_FOUND";

const USERS_FOUND = "USERS_FOUND";

module.exports = {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    REGISTER_SUCCESS,
    INTERNAL_SERVER_ERROR,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    USER_FOUND,
    USER_NOT_FOUND,
    USERS_FOUND
};
