export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const COULD_NOT_CONNECT_TO_SERVER = "COULD_NOT_CONNECT_TO_SERVER";

export const COULD_NOT_DECODE_TOKEN = "COULD_NOT_DECODE_TOKEN";
